robot_1:
  vehicleHeight: 0.75
  cameraOffsetZ: 0.0
  vehicleX: 0.0
  vehicleY: 0.0
  vehicleZ: 0.0
  terrainZ: 0.0
  vehicleYaw: 0.0

robot_2:
  vehicleHeight: 0.75
  cameraOffsetZ: 0.0
  vehicleX: 10.0
  vehicleY: 0.0
  vehicleZ: 0.0
  terrainZ: 0.0
  vehicleYaw: 0.0
